// myvideo-react/src/components/video/Playlist.js
import * as React from "react";

class Playlist extends React.Component {
    constructor(props) {
        super(props)
        this.state={
            playlist:[],
            url:"",
            id:""
        }

    }


    playVideo = (id, url) => {

        this.setState({id: id, url: url})
        this.props.changeVideo(id,url)
    }

    componentDidMount(){
        fetch("http://localhost:53000/playlist?status=1", {method: 'GET'})
            .then(response => response.json())
            .then(data => {
                debugger
                this.setState({playlist: data})
            })
            .catch(e => {
                console.log("error")
            })
    }

    render() {
        const list=this.state.playlist;
        return (
            <div>
                <p className="navbar-brand">Vides - FSD </p>
                <ul className="nav  nav-pills flex-column ">
                    { list.map((item)=>{
                        return <li className="nav-item">
                            <a className="nav-link" href="javascript:void(0)"  onClick={()=>this.playVideo(item.id,item.url)}>
                                <i className="fa fa-play-circle fa-1x text-info">{item.title}</i>
                            </a>
                        </li>
                    })}

                </ul>

            </div>
        );
    }
}

export default Playlist;

// myvideo-ag/src/app/components/playlist/playlist.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import {Videoservice} from "../video-player/videoservice";

@Component({
  selector: 'app-playlist',
  templateUrl: './playlist.component.html',
  styleUrls: ['./playlist.component.css']
})
export class PlaylistComponent implements OnInit {

  constructor(private http: HttpClient,public videoservice: Videoservice,) { }
   playlistUrl = 'http://localhost:53000/playlist'

  playlist: any ;

  ngOnInit() {
    this.getPlaylist(this.playlistUrl+"?status=1").subscribe(data =>{
      /* get请求成功时的回调处理 */
      // console.info(data);
      this.playlist =data;
      this.videoservice.playlist = this.playlist;
      this.videoservice.changeVideo(data[0].url,data[0].id);
    },xhr =>{
      /* get失败时返回 XMLHttpRequest 对象实例信息 */
      console.log(xhr.error.text); /* 输出错误文本信息 */
    });

  }

  getPlaylist(url) {
    return this.http.get(url);
  }

  playVideo(id) {
    this.getPlaylist(this.playlistUrl+"?id="+id).subscribe(data =>{
      /* get请求成功时的回调处理 */
      // console.log(data);

      this.videoservice.changeVideo(data[0].url,data[0].id);
    },xhr =>{
      /* get失败时返回 XMLHttpRequest 对象实例信息 */
      console.log(xhr.error.text); /* 输出错误文本信息 */
    });
  }
}

<p class="navbar-brand">Vides - FSD </p>
<ul class="nav  nav-pills flex-column "  *ngFor="let item of playlist">

    <li class="nav-item" >
        <a class="nav-link" href="javascript:void(0)" (click)="playVideo(item.id)" >
          <i class="fa fa-play-circle fa-1x text-info">{{item.title}}</i></a></li>

</ul>
