// myvideo-react/src/App.js
import React from 'react';
import Videoplayer from "./components/video/Videoplayer";
import NewVideo from "./components/NewVideo";
import {BrowserRouter as Router, Route, Link} from 'react-router-dom';
function App() {
  return (
      <Router>
    <div className="App">
        <nav className="navbar fixed-top navbar-expand-sm bg-primary navbar-dark">
            <a className="navbar-brand" href="#">lunas</a>
            <ul className="navbar-nav">

                <li className="nav-item ">
                    <a className="nav-link" href='/'>video player</a>
                </li>
                <li className="nav-item">
                    <a className="nav-link" href='/newvideo'>new video</a>
                </li>

            </ul>
        </nav>
        <br/>
        <br/>
        <br/>
        <Route exact path="/" component={Videoplayer} />
        <Route path="/newvideo" component={NewVideo} />

    </div>
      </Router>
  );
}

export default App;

// myvideo-ag/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'myvideo-ag';
}

<div class="container">


  <nav class="navbar fixed-top navbar-expand-sm bg-primary navbar-dark">
    <a class="navbar-brand" href="#">lunas</a>
    <ul class="navbar-nav">

      <li class="nav-item ">
        <a routerLink="/video-player" routerLinkActive="active" class="nav-link">video player</a>
      </li>
      <li class="nav-item">
        <a routerLink="/new-video" routerLinkActive="active" class="nav-link">new video</a>
      </li>

    </ul>
  </nav>

</div>

<router-outlet></router-outlet>
