// myvideo-ag/src/app/components/new-video/new-video.component.ts
import { Component, OnInit } from '@angular/core';
import { VideoInfo }    from './videoInfo';
import {HttpClient, HttpErrorResponse, HttpHeaders} from '@angular/common/http';
import uuidv4 from "uuid/v4";
import { FormControl, FormGroup, Validators } from '@angular/forms';
import {throwError} from "rxjs";
import {catchError} from "rxjs/operators";
const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type':  'application/json',
    'Authorization': 'my-auth-token'
  })
};

@Component({
  selector: 'app-new-video',
  templateUrl: './new-video.component.html',
  styleUrls: ['./new-video.component.css']
})


export class NewVideoComponent implements OnInit {

  constructor(private http: HttpClient,) { }

  playlistUrl = 'http://localhost:53000/playlist'

  playlist: any ;



  ngOnInit() {
    this.getPlaylist(this.playlistUrl);

  }

  getPlaylist(url) {

    this.http.get(url).subscribe(data =>{
      /* get请求成功时的回调处理 */
      // console.info(data);
      this.playlist =data;

    },xhr =>{
      /* get失败时返回 XMLHttpRequest 对象实例信息 */
      console.log(xhr.error.text); /* 输出错误文本信息 */
    });
  }
  model = new VideoInfo("","","","","") ;

  submitted = false;

  onSubmit() {
    this.model.status='0';
    if(this.model.id==''&&this.model.status==''){

      this.model.id= uuidv4();
      this.http.post(this.playlistUrl, this.model, httpOptions)
        .subscribe(
          data => {
            console.log("POST Request is successful ", data);
            this.newVideo()
            this.getPlaylist(this.playlistUrl);
          },
          error => {
            console.log("Error", error);
          }
        );
      ;
    }else{

        this.http.put(this.playlistUrl+"/"+this.model.id,
          this.model)
          .subscribe(
            data => {
              console.log("PUT Request is successful ", data);
              this.getPlaylist(this.playlistUrl);
            },
            error => {
              console.log("Rrror", error);
            }
          );


    }

  }

  // TODO: Remove this when we're done
  get diagnostic() { return JSON.stringify(this.model); }

  edit(id:string) {

    this.http.get(this.playlistUrl+"?id="+id).subscribe(data =>{
      /* get请求成功时的回调处理 */
      // console.log(data);
      this.model=data[0]
      this.model.status='0'
      for(let i=0;i<this.playlist.length;i++){
        let item = this.playlist[i];
        if(item.id==id){
          item.status='0';
        }
      }
    },xhr =>{
      /* get失败时返回 XMLHttpRequest 对象实例信息 */
      console.log(xhr.error.text); /* 输出错误文本信息 */
    });
  }

  delete(id: any) {
    this.http.delete(this.playlistUrl+"/"+id)
      .subscribe(
        data => {
          console.log("DELETE Request is successful ", data);
          this.getPlaylist(this.playlistUrl);
        },
        error => {
          console.log("Error", error);
        }
      );

  }

  approve(id: any) {
    this.http.get(this.playlistUrl+"?id="+id).subscribe(data =>{
      /* get请求成功时的回调处理 */
      // console.log(data);
      data[0].status='1'
      this.http.put(this.playlistUrl+"/"+id,
        data[0])
        .subscribe(
          data => {
            console.log("PUT Request is successful ", data);
            this.getPlaylist(this.playlistUrl);
          },
          error => {
            console.log("Rrror", error);
          }
        );
    },xhr =>{
      /* get失败时返回 XMLHttpRequest 对象实例信息 */
      console.log(xhr.error.text); /* 输出错误文本信息 */
    });


  }

  newVideo() {
    this.model = new VideoInfo("","","","","") ;
  }
}

<div class="container-fluid" style="margin-top: 80px;width:90%;">
  <h1>new video Form</h1>
  <form (ngSubmit)="onSubmit()" #videoForm="ngForm" appIdentityRevealed>
    <div [hidden]="videoForm.submitted">
      <div class="cross-validation" [class.cross-validation-error]="videoForm.errors?.identityRevealed && (videoForm.touched || videoForm.dirty)">
        <div class="form-group">
          <label for="title">title</label>
          <input type="hidden" class="form-control" id="id" [(ngModel)]="model.id" name="id">
          <input type="text" class="form-control" id="title" [(ngModel)]="model.title" name="title" required appForbiddenName="bob" #title="ngModel">
          <div *ngIf="title.invalid && (title.dirty || title.touched)"
               class="alert alert-danger">

            <div *ngIf="title.errors.required">
              title is required.
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="url">url</label>
          <input type="url" class="form-control" id="url" [(ngModel)]="model.url" name="url" required #url="ngModel">
          <div *ngIf="url.invalid && (url.dirty || url.touched)"
               class="alert alert-danger">

            <div *ngIf="url.errors.required">
              url is required.
            </div>
            <div *ngIf="url.errors.url">
              bad url.
            </div>
          </div>

        </div>

        <button type="submit" class="btn btn-success" [disabled]="videoForm.invalid">save</button>&nbsp;
      </div>

    </div>
    <div class="submitted-message" *ngIf="videoForm.submitted">
      <p>You've submitted your video, {{ videoForm.value.title }}!</p>
      <button (click)="videoForm.resetForm({})"  class="btn btn-success">Add new video</button>
    </div>

  </form>
  <br/>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>no</th>
      <th>title</th>
      <th>url</th>
      <th>operate</th>
    </tr>
    </thead>
    <tbody *ngFor="let item of playlist; let i = index">
    <tr>
      <td>{{i + 1}}</td>
      <td>{{item.title}}</td>
      <td>{{item.url}}</td>
      <td>
        <button type="button" class="btn btn-primary" (click)="videoForm.resetForm({});edit(item.id)" >edit</button>
        &nbsp;
        <button type="button" class="btn btn-danger" (click)="delete(item.id)">delete</button>
        &nbsp;
        <button type="button" class="btn btn-success" (click)="approve(item.id)" [disabled]="item.status=='1'">approve</button>
      </td>
    </tr>
    </tbody>
  </table>
</div>

// myvideo-react/src/components/NewVideo.js
import * as React from "react";

var uuid = require('react-native-uuid');

class NewVideo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            playlist: [],
            id:"",
            url:"",
            title:""
        }
    }


    submitForm = (e) => {
        let url='http://localhost:53000/playlist/'

        let id = this.state.id;
        let method="PUT"
        if (typeof id == 'undefined' || id == '') {
            id = uuid.v1();
            method="POST"
        }else{
            url =url+id
        }

        fetch(url, {
            method: method,
            headers:{
                'Accept':'application/json',
                'Content-Type':'application/json',
            },
            body: JSON.stringify({
                id: id,
                title:this.state.title,
                url:this.state.url,
                status:"0",
                disableStatus:""
            }),
        }).then((response) => {
            if (response.ok) {
                return response.json();
            }
        }).then((json) => {
            // alert(JSON.stringify(json));
            this.loadPlaylist()
            this.initState()
        }).catch((error) => {
            console.error(error);
        })
    }

    idChange = (e) => {
        this.setState({
            id: e.target.value
        })
    }

    titleChange = (e) => {
        this.setState({
            title: e.target.value
        })
        console.log("title",e.target.value)
    }

    urlChange = (e) => {
        this.setState({
            url: e.target.value
        })
    }

    edit = (id) => {
        fetch("http://localhost:53000/playlist/"+id, {method: 'GET'})
            .then(response => response.json())
            .then(data => {
                this.setState({
                    id:data.id,
                    url:data.url,
                    title:data.title,
                    status:data.status,
                    disableStatus:data.disableStatus
                })

            })
            .catch(e => {
                console.log("error")
            })


    }

    del = (id) => {
        fetch("http://localhost:53000/playlist/"+id, {method: 'DELETE'})
            .then(response => response.json())
            .then(data => {
                this.loadPlaylist()

            })
            .catch(e => {
                console.log("error")
            })
    }

    approve = (id) => {
        fetch("http://localhost:53000/playlist/"+id, {method: 'GET'})
            .then(response => response.json())
            .then(data => {

                fetch("http://localhost:53000/playlist/"+id, {
                    method: "PUT",
                    headers:{
                        'Accept':'application/json',
                        'Content-Type':'application/json',
                    },
                    body: JSON.stringify({
                        id:data.id,
                        url:data.url,
                        title:data.title,
                        status:"1",
                        disableStatus:"disabled"
                    }),
                }).then((response) => {
                    if (response.ok) {
                        return response.json();
                    }
                }).then((json) => {
                    // alert(JSON.stringify(json));
                    this.loadPlaylist()
                    this.initState()
                }).catch((error) => {
                    console.error(error);
                })
            })
            .catch(e => {
                console.log("error")
            })

    }


    componentDidMount() {
        this.loadPlaylist()
    }

    loadPlaylist(){
        fetch("http://localhost:53000/playlist", {method: 'GET'})
            .then(response => response.json())
            .then(data => {
                this.setState({playlist: data})
            })
            .catch(e => {
                console.log("error")
            })
    }
    render() {
        const list = this.state.playlist;
        return (
            <div className="newvideo">
                <form onSubmit={this.submitForm}>

                    <div className="form-group">
                        <label htmlFor="title">title</label>
                        <input type="text" className="form-control"   required value={this.state.title} onChange={this.titleChange}/>

                    </div>

                    <div className="form-group">
                        <label htmlFor="url">url</label>
                        <input type="url" className="form-control"  required value={this.state.url} onChange={this.urlChange}/>

                    </div>
                    <div>
                        <button type="submit" className="btn btn-success" >save</button>
                    </div>

                </form>

                <br/>
                <table className="table table-striped">
                    <thead>
                    <tr>
                        <th>no</th>
                        <th>title</th>
                        <th>url</th>
                        <th>operate</th>
                    </tr>
                    </thead>
                    <tbody>
                    {list.map((item, index) => {
                        return <tr key={item.id}>
                            <td>{index + 1}</td>
                            <td>{item.title}</td>
                            <td>{item.url}</td>
                            <td>
                                <button type="button" className="btn btn-primary" onClick={this.edit.bind(this,item.id)}>edit</button>
                                &nbsp;
                                <button type="button" className="btn btn-danger" onClick={this.del.bind(this,item.id)}>delete</button>
                                &nbsp;
                                <button type="button" className="btn btn-success" disabled={item.disableStatus} onClick={this.approve.bind(this,item.id)}>approve</button>
                            </td>
                        </tr>

                    })}
                    </tbody>
                </table>
            </div>
        );
    }

    initState() {
        this.setState( {
            id:"",
            url:"",
            title:""
        })
    }
}

export default NewVideo;
